export const PRICING_CONTENT = {
    header: {
        title: 'Investment',
        description: 'Transparent pricing for organizations of every scale.',
    },
    toggle: {
        monthly: 'Monthly',
        annual: 'Annual',
        discountLabel: '(Save 20%)',
    },
    tiers: [
        {
            name: 'Starter',
            monthlyPrice: '0',
            annualPrice: '0',
            billingSuffix: '',
            subtitle: '',
            features: ['5 events/mo', 'Standard Templates', 'Email Support'],
            ctaText: 'START FREE',
            ctaLink: 'https://sapp.feedbackcert.com',
            popular: false,
        },
        {
            name: 'Growth',
            monthlyPrice: '19',
            annualPrice: '15',
            billingSuffix: '/ mo',
            subtitle: 'Scale with confidence.',
            features: [
                '25 Events/mo',
                'Custom Templates',
                'Basic Analytics',
                'Certificate Branding',
                'Email Support',
            ],
            ctaText: 'GET STARTED',
            ctaLink: 'https://sapp.feedbackcert.com',
            popular: false,
        },
        {
            name: 'Professional',
            monthlyPrice: '49',
            annualPrice: '39',
            billingSuffix: '/ mo',
            subtitle: 'Unlocked potential.',
            features: [
                'Unlimited Events',
                'Logic Jumping',
                'Vector Certs',
                'Deep Analytics',
                'Priority Support',
            ],
            ctaText: 'GET ACCESS',
            ctaLink: 'https://sapp.feedbackcert.com',
            popular: true,
        },
        {
            name: 'Enterprise',
            monthlyPrice: 'Custom',
            annualPrice: 'Custom',
            billingSuffix: '',
            subtitle: '',
            features: [
                'SSO & SLA',
                'Dedicated Success Mgr',
                'Custom Integration',
                'Audit Logs',
            ],
            ctaText: 'CONTACT US',
            ctaTarget: 'contact',
            popular: false,
        },
    ],
};
